"""ORM 模型包：导入本包即完成全部表的元数据注册。"""

from app.models.base import Base, TimestampMixin, UTCDateTime
from app.models.cash import (
    DIRECTIONS,
    MATERIAL_FIELDS,
    STATES,
    AnalysisResult,
    CashEvent,
    CashEventRevision,
    Scenario,
    ScenarioEventOverride,
    SourceRecord,
)
from app.models.consultation import (
    CASE_STATUSES,
    CASE_STATUS_LABELS,
    CONSULTATION_ALLOWED_FIELDS,
    CONSULTATION_FORBIDDEN_FIELDS,
    QUESTION_TYPE_LABELS,
    AuditLog,
    ConsultationCase,
    ConsultationUpdate,
)
from app.models.household import (
    CARD_TYPES,
    MEMBERSHIP_STATUSES,
    REACTION_TYPES,
    Household,
    HouseholdCard,
    HouseholdCardComment,
    HouseholdCardReaction,
    HouseholdCardRecipient,
    HouseholdMembership,
)
from app.models.imports import BATCH_COMMITTED, BATCH_PREVIEW, ImportBatch
from app.models.merchant import (
    SOURCE_AI_EXTRACT,
    SOURCE_CONSULTATION,
    SOURCE_CSV_IMPORT,
    SOURCE_MANUAL,
    BusinessAccountSnapshot,
    MerchantProfile,
)
from app.models.user import (
    ALL_ROLES,
    ROLE_ADMIN,
    ROLE_CONSULTANT,
    ROLE_FAMILY_MEMBER,
    ROLE_MERCHANT,
    RefreshSession,
    User,
    UserRole,
)

__all__ = [
    "ALL_ROLES",
    "AnalysisResult",
    "AuditLog",
    "BATCH_COMMITTED",
    "BATCH_PREVIEW",
    "Base",
    "BusinessAccountSnapshot",
    "CARD_TYPES",
    "CASE_STATUSES",
    "CASE_STATUS_LABELS",
    "CONSULTATION_ALLOWED_FIELDS",
    "CONSULTATION_FORBIDDEN_FIELDS",
    "CashEvent",
    "CashEventRevision",
    "ConsultationCase",
    "ConsultationUpdate",
    "DIRECTIONS",
    "Household",
    "HouseholdCard",
    "HouseholdCardComment",
    "HouseholdCardReaction",
    "HouseholdCardRecipient",
    "HouseholdMembership",
    "ImportBatch",
    "MATERIAL_FIELDS",
    "MEMBERSHIP_STATUSES",
    "MerchantProfile",
    "QUESTION_TYPE_LABELS",
    "REACTION_TYPES",
    "ROLE_ADMIN",
    "ROLE_CONSULTANT",
    "ROLE_FAMILY_MEMBER",
    "ROLE_MERCHANT",
    "RefreshSession",
    "STATES",
    "SOURCE_AI_EXTRACT",
    "SOURCE_CONSULTATION",
    "SOURCE_CSV_IMPORT",
    "SOURCE_MANUAL",
    "Scenario",
    "ScenarioEventOverride",
    "SourceRecord",
    "TimestampMixin",
    "UTCDateTime",
    "User",
    "UserRole",
]
