import test from 'node:test';
import assert from 'node:assert/strict';
import {evaluate, demoInput, yuanToCents, makeConsultationPacket} from '../core/cash-engine.mjs';
const base = () => {const x=demoInput(); x.scenarios=[x.scenarios[0]]; return x;};
const blocked = x => assert.equal(evaluate(x).status,'INPUT_INCOMPLETE');

test('01 按时情景：1200，期末未提用1800',()=>{const r=evaluate(base()); assert.equal(r.maxWithdrawalCents,120000);assert.equal(r.scenarios[0].endingBeforeWithdrawalCents,180000);});
test('02 延迟：支付差200，留底差800，上限0',()=>{const r=evaluate(demoInput());assert.equal(r.status,'PAYMENT_GAP');assert.equal(r.maxWithdrawalCents,0);assert.equal(r.paymentGapCents,20000);assert.equal(r.bufferGapCents,80000);assert.equal(r.scenarios[1].endingBeforeWithdrawalCents,180000);assert.equal(r.scenarios[1].pendingAtLimit[0].eventId,'settlement');assert.deepEqual(r.scenarios[1].pendingAtLimit[0].sourceRefs,['simulated:settlement']);});
test('03 提用1200后按时情景期末600',()=>{const x=base();x.openingCents-=120000;const r=evaluate(x);assert.equal(r.maxWithdrawalCents,0);assert.equal(r.status,'FEASIBLE');assert.equal(r.scenarios[0].endingBeforeWithdrawalCents,60000);});
test('04 不提用也低于留底，但能付款',()=>{const x=base();x.openingCents=230000;const r=evaluate(x);assert.equal(r.status,'BELOW_BUFFER');assert.equal(r.paymentGapCents,0);assert.equal(r.bufferGapCents,10000);});
test('05 t0约束：未来收入不能让今天提走超过已有钱',()=>{const x=base();x.events=x.events.filter(e=>e.deltaCents>0);assert.equal(evaluate(x).maxWithdrawalCents,300000);});
test('06 没有事件仍检查当前留底',()=>{const x=base();x.events=[];assert.equal(evaluate(x).maxWithdrawalCents,300000);});
test('07 负的期初余额立即显示支付缺口',()=>{const x=base();x.events=[];x.openingCents=-100;assert.equal(evaluate(x).paymentGapCents,100);});
test('08 负留底拒绝',()=>{const x=base();x.reserveCents=-1;blocked(x);});
test('09 空情景拒绝',()=>{const x=base();x.scenarios=[];blocked(x);});
test('10 重复事件ID拒绝',()=>{const x=base();x.events.push({...x.events[0]});blocked(x);});
test('11 不同ID同一现金流水拒绝重复计入',()=>{const x=base();x.events.push({...x.events[0],id:'copy'});blocked(x);});
test('12 已包含期初的历史流水不二次计入',()=>{const x=base();x.events.push({...x.events[1],id:'past',cashKey:'past',at:x.asOf-1,state:'included_in_opening'});assert.equal(evaluate(x).maxWithdrawalCents,120000);});
test('13 未来流水不得已算入期初',()=>{const x=base();x.events[1].state='included_in_opening';blocked(x);});
test('14 待结算以未来现金事件计算，今天不能加进余额',()=>{const r=evaluate(base());assert.equal(r.scenarios[0].points[0].balanceCents,360000);});
test('15 同时间未知先后按支出先行',()=>{const x=base();x.events[1].at=x.events[2].at;assert.equal(evaluate(x).maxWithdrawalCents,0);assert.equal(evaluate(x).status,'BELOW_BUFFER');});
test('16 修改日期后重算改变结论，保留来源',()=>{const x=base();x.events[1].at=demoInput().scenarios[1].timeOverrides.settlement;const r=evaluate(x);assert.equal(r.status,'PAYMENT_GAP');assert.ok(r.limitingPoint.causalEventIds.includes('rent'));assert.deepEqual(r.limitingPoint.sourceRefs,['simulated:refund']);});
test('17 收入延期在同一固定事件集下不提高上限',()=>{const x=base(), initial=evaluate(x).maxWithdrawalCents;for(let day=0;day<=6;day++){const y=base();y.events[1].at+=day*86400000;assert.ok(evaluate(y).maxWithdrawalCents<=initial);}});
test('18 期末之后的到账不能用于7日内支付',()=>{const x=base();x.events[1].at=x.end+1;assert.equal(evaluate(x).paymentGapCents,20000);});
test('19 期间留底升高必须新增检查点',()=>{const x=base();x.reserveChanges=[{at:x.end-1,cents:200000}];assert.equal(evaluate(x).bufferGapCents,20000);});
test('20 未知时间拒绝给上限',()=>{const x=base();x.events[0].at=null;blocked(x);});
test('21 未知金额拒绝给上限',()=>{const x=base();x.events[0].deltaCents=null;blocked(x);});
test('22 未确认义务完整性拒绝',()=>{const x=base();x.obligationsConfirmed=false;blocked(x);});
test('23 未确认期初余额拒绝',()=>{const x=base();x.balanceConfirmed=false;blocked(x);});
test('24 非整数分拒绝',()=>{const x=base();x.events[0].deltaCents=1.1;blocked(x);});
test('25 多币种拒绝',()=>{const x=base();x.events[1].currency='USD';blocked(x);});
test('26 未确认来源拒绝',()=>{const x=base();x.events[0].sourceRefs=[];blocked(x);});
test('27 未知状态拒绝',()=>{const x=base();x.events[0].state='processing';blocked(x);});
test('28 撤销现金事件不计入未来',()=>{const x=base();x.events[3].state='cancelled';assert.equal(evaluate(x).maxWithdrawalCents,160000);});
test('29 相同时间的期初边界需消歧',()=>{const x=base();x.events[0].at=x.asOf;blocked(x);});
test('30 单池内部转账期末不增钱，在途中降低可用',()=>{const x=base();x.events=[];x.events.push({id:'out',cashKey:'out',deltaCents:-100000,at:x.asOf+1000,currency:'CNY',confirmed:true,state:'scheduled',sourceRefs:['transfer']},{id:'in',cashKey:'in',deltaCents:100000,at:x.asOf+2000,currency:'CNY',confirmed:true,state:'scheduled',sourceRefs:['transfer']});const r=evaluate(x);assert.equal(r.maxWithdrawalCents,200000);assert.equal(r.scenarios[0].endingBeforeWithdrawalCents,360000);});
test('31 金额字符串精确转分',()=>{assert.equal(yuanToCents('0.10'),10);assert.equal(yuanToCents('1.01'),101);assert.equal(yuanToCents('-0.01'),-1);assert.throws(()=>yuanToCents('1.001'));assert.throws(()=>yuanToCents('1e3'));});
test('32 累加溢出拒绝',()=>{const x=base();x.openingCents=Number.MAX_SAFE_INTEGER;x.events=x.events.filter(e=>e.deltaCents>0);blocked(x);});
test('33 情景不能引用不存在的记录',()=>{const x=base();x.scenarios[0].timeOverrides={missing:x.end};blocked(x);});
test('34 输入不被引擎更改',()=>{const x=base(), snapshot=JSON.stringify(x);evaluate(x);assert.equal(JSON.stringify(x),snapshot);});
test('35 咨询白名单排除家庭和派生余额字段',()=>{const facts=[{id:'payout',scope:'business',kind:'settlement',amountCents:200000,expectedAt:123,status:'pending',sourceLabel:'模拟结算通知',openingCents:360000,privateNote:'secret'},{id:'home',scope:'household',kind:'expense',amountCents:100}];const r=makeConsultationPacket(facts,['payout','home'],'请核对预计到账日期',1);assert.equal(r.facts.length,1);assert.ok(!JSON.stringify(r).includes('secret'));assert.equal(r.facts[0].openingCents,undefined);});
test('36 两情景期末比较均为尚未提用',()=>{const r=evaluate(demoInput());assert.deepEqual(r.scenarios.map(s=>s.endingBeforeWithdrawalCents),[180000,180000]);});
