"""initial schema

Revision ID: 0053fb3fa9b7
Revises: 
Create Date: 2026-10-02 14:28:43.464005
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import sqlalchemy as sa

revision: str = '0053fb3fa9b7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_name', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=48), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('merchant_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_actor_created', ['actor_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index('ix_audit_logs_resource', ['resource_type', 'resource_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('merchant_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('business_name', sa.String(length=128), nullable=False),
    sa.Column('business_type', sa.String(length=64), nullable=False),
    sa.Column('contact_name', sa.String(length=64), nullable=True),
    sa.Column('phone_optional', sa.String(length=32), nullable=True),
    sa.Column('default_currency', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('default_buffer_amount_cents', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=128), nullable=False),
    sa.Column('account_masked_no', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_merchant_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchant_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_merchant_profiles_user_id'))
    )
    with op.batch_alter_table('merchant_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merchant_profiles_created_at'), ['created_at'], unique=False)

    op.create_table('refresh_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('rotated_to', sa.String(length=36), nullable=True),
    sa.Column('remember', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_sessions_token_hash'))
    )
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_refresh_sessions_user_active', ['user_id', 'revoked_at'], unique=False)

    op.create_table('user_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role', name='uq_user_roles_user_role')
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_user_id'), ['user_id'], unique=False)

    op.create_table('business_account_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('opening_balance_cents', sa.Integer(), nullable=False),
    sa.Column('pending_settlement_cents', sa.Integer(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant_profiles.id'], name=op.f('fk_business_account_snapshots_merchant_id_merchant_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_account_snapshots'))
    )
    with op.batch_alter_table('business_account_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_account_snapshots_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_account_snapshots_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_account_snapshots_snapshot_at'), ['snapshot_at'], unique=False)

    op.create_table('households',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('invite_code', sa.String(length=16), nullable=False),
    sa.Column('invite_code_rotated_at', sa.DateTime(), nullable=True),
    sa.Column('invite_code_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant_profiles.id'], name=op.f('fk_households_merchant_id_merchant_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_households_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_households'))
    )
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_households_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_households_invite_code'), ['invite_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_households_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_households_owner_id'), ['owner_id'], unique=False)

    op.create_table('scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant_profiles.id'], name=op.f('fk_scenarios_merchant_id_merchant_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenarios'))
    )
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenarios_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenarios_merchant_id'), ['merchant_id'], unique=False)

    op.create_table('source_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('stored_file_name', sa.String(length=255), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('import_batch_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant_profiles.id'], name=op.f('fk_source_records_merchant_id_merchant_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_records'))
    )
    with op.batch_alter_table('source_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_records_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_records_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index('ix_source_records_merchant_created', ['merchant_id', 'created_at'], unique=False)

    op.create_table('analysis_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('scenario_id', sa.String(length=36), nullable=True),
    sa.Column('scenario_ids', sa.JSON(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('max_withdrawable_cents', sa.Integer(), nullable=True),
    sa.Column('opening_balance_cents', sa.Integer(), nullable=False),
    sa.Column('buffer_cents', sa.Integer(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), nullable=False),
    sa.Column('window_end_at', sa.DateTime(), nullable=False),
    sa.Column('limiting_timestamp', sa.DateTime(), nullable=True),
    sa.Column('limiting_balance_cents', sa.Integer(), nullable=True),
    sa.Column('limiting_event_id', sa.String(length=36), nullable=True),
    sa.Column('payment_gap_cents', sa.Integer(), nullable=False),
    sa.Column('buffer_gap_cents', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('events_version_hash', sa.String(length=64), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('stale_reason', sa.String(length=255), nullable=True),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant_profiles.id'], name=op.f('fk_analysis_results_merchant_id_merchant_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_analysis_results_scenario_id_scenarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['business_account_snapshots.id'], name=op.f('fk_analysis_results_snapshot_id_business_account_snapshots'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_results'))
    )
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_results_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_results_is_stale'), ['is_stale'], unique=False)
        batch_op.create_index('ix_analysis_results_merchant_created', ['merchant_id', 'created_at'], unique=False)

    op.create_table('cash_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('cash_key', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_label', sa.String(length=128), nullable=True),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('sequence_index_optional', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant_profiles.id'], name=op.f('fk_cash_events_merchant_id_merchant_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_cash_events_source_record_id_source_records'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_events')),
    sa.UniqueConstraint('merchant_id', 'cash_key', name='uq_cash_events_merchant_cash_key')
    )
    with op.batch_alter_table('cash_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_cash_events_merchant_scheduled', ['merchant_id', 'scheduled_at'], unique=False)

    op.create_table('household_cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('card_type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('shared_fields', sa.JSON(), nullable=False),
    sa.Column('analysis_result_id', sa.String(length=36), nullable=True),
    sa.Column('cash_event_id', sa.String(length=36), nullable=True),
    sa.Column('planned_household_amount_cents', sa.Integer(), nullable=True),
    sa.Column('system_max_withdrawable_cents', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_household_cards_household_id_households'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant_profiles.id'], name=op.f('fk_household_cards_merchant_id_merchant_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_household_cards'))
    )
    with op.batch_alter_table('household_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_household_cards_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_household_cards_household_id'), ['household_id'], unique=False)
        batch_op.create_index('ix_household_cards_merchant_created', ['merchant_id', 'created_at'], unique=False)

    op.create_table('household_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('household_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('relation_label', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_household_memberships_household_id_households'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_household_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_household_memberships')),
    sa.UniqueConstraint('household_id', 'user_id', name='uq_household_memberships_household_user')
    )
    with op.batch_alter_table('household_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_household_memberships_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_household_memberships_user_status', ['user_id', 'status'], unique=False)

    op.create_table('cash_event_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cash_event_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('changed_fields', sa.JSON(), nullable=False),
    sa.Column('material', sa.Boolean(), nullable=False),
    sa.Column('change_reason', sa.String(length=255), nullable=True),
    sa.Column('changed_by', sa.String(length=36), nullable=True),
    sa.Column('changed_by_name', sa.String(length=64), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cash_event_id'], ['cash_events.id'], name=op.f('fk_cash_event_revisions_cash_event_id_cash_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_event_revisions')),
    sa.UniqueConstraint('cash_event_id', 'version', name='uq_cash_event_revisions_event_version')
    )
    with op.batch_alter_table('cash_event_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_event_revisions_cash_event_id'), ['cash_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_event_revisions_changed_at'), ['changed_at'], unique=False)

    op.create_table('consultation_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_no', sa.String(length=32), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('cash_event_id', sa.String(length=36), nullable=True),
    sa.Column('cash_event_version', sa.Integer(), nullable=True),
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('ai_draft', sa.Text(), nullable=True),
    sa.Column('shared_fields', sa.JSON(), nullable=False),
    sa.Column('allowed_field_names', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assignee_id', sa.String(length=36), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('resolution_fields', sa.JSON(), nullable=False),
    sa.Column('provider_key', sa.String(length=32), nullable=False),
    sa.Column('external_reference', sa.String(length=64), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cash_event_id'], ['cash_events.id'], name=op.f('fk_consultation_cases_cash_event_id_cash_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant_profiles.id'], name=op.f('fk_consultation_cases_merchant_id_merchant_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultation_cases'))
    )
    with op.batch_alter_table('consultation_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultation_cases_case_no'), ['case_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_consultation_cases_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_consultation_cases_merchant_created', ['merchant_id', 'created_at'], unique=False)
        batch_op.create_index('ix_consultation_cases_status', ['status', 'updated_at'], unique=False)

    op.create_table('household_card_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['household_cards.id'], name=op.f('fk_household_card_comments_card_id_household_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_household_card_comments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_household_card_comments'))
    )
    with op.batch_alter_table('household_card_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_household_card_comments_card_id'), ['card_id'], unique=False)

    op.create_table('household_card_reactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('reaction', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['household_cards.id'], name=op.f('fk_household_card_reactions_card_id_household_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_household_card_reactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_household_card_reactions'))
    )
    with op.batch_alter_table('household_card_reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_household_card_reactions_card_id'), ['card_id'], unique=False)

    op.create_table('household_card_recipients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('reaction', sa.String(length=16), nullable=True),
    sa.Column('reacted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['household_cards.id'], name=op.f('fk_household_card_recipients_card_id_household_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_household_card_recipients_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_household_card_recipients')),
    sa.UniqueConstraint('card_id', 'user_id', name='uq_household_card_recipients_card_user')
    )
    with op.batch_alter_table('household_card_recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_household_card_recipients_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_household_card_recipients_user', ['user_id', 'is_read'], unique=False)

    op.create_table('scenario_event_overrides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('cash_event_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_at_override', sa.DateTime(), nullable=True),
    sa.Column('amount_cents_override', sa.Integer(), nullable=True),
    sa.Column('direction_override', sa.String(length=16), nullable=True),
    sa.Column('state_override', sa.String(length=24), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cash_event_id'], ['cash_events.id'], name=op.f('fk_scenario_event_overrides_cash_event_id_cash_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_scenario_event_overrides_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_event_overrides')),
    sa.UniqueConstraint('scenario_id', 'cash_event_id', name='uq_scenario_overrides_scenario_event')
    )
    with op.batch_alter_table('scenario_event_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenario_event_overrides_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenario_event_overrides_scenario_id'), ['scenario_id'], unique=False)

    op.create_table('consultation_updates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_name', sa.String(length=64), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('visible_to_merchant', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['consultation_cases.id'], name=op.f('fk_consultation_updates_case_id_consultation_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultation_updates'))
    )
    with op.batch_alter_table('consultation_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultation_updates_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultation_updates_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultation_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultation_updates_created_at'))
        batch_op.drop_index(batch_op.f('ix_consultation_updates_case_id'))

    op.drop_table('consultation_updates')
    with op.batch_alter_table('scenario_event_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenario_event_overrides_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_scenario_event_overrides_created_at'))

    op.drop_table('scenario_event_overrides')
    with op.batch_alter_table('household_card_recipients', schema=None) as batch_op:
        batch_op.drop_index('ix_household_card_recipients_user')
        batch_op.drop_index(batch_op.f('ix_household_card_recipients_created_at'))

    op.drop_table('household_card_recipients')
    with op.batch_alter_table('household_card_reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_household_card_reactions_card_id'))

    op.drop_table('household_card_reactions')
    with op.batch_alter_table('household_card_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_household_card_comments_card_id'))

    op.drop_table('household_card_comments')
    with op.batch_alter_table('consultation_cases', schema=None) as batch_op:
        batch_op.drop_index('ix_consultation_cases_status')
        batch_op.drop_index('ix_consultation_cases_merchant_created')
        batch_op.drop_index(batch_op.f('ix_consultation_cases_created_at'))
        batch_op.drop_index(batch_op.f('ix_consultation_cases_case_no'))

    op.drop_table('consultation_cases')
    with op.batch_alter_table('cash_event_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_event_revisions_changed_at'))
        batch_op.drop_index(batch_op.f('ix_cash_event_revisions_cash_event_id'))

    op.drop_table('cash_event_revisions')
    with op.batch_alter_table('household_memberships', schema=None) as batch_op:
        batch_op.drop_index('ix_household_memberships_user_status')
        batch_op.drop_index(batch_op.f('ix_household_memberships_created_at'))

    op.drop_table('household_memberships')
    with op.batch_alter_table('household_cards', schema=None) as batch_op:
        batch_op.drop_index('ix_household_cards_merchant_created')
        batch_op.drop_index(batch_op.f('ix_household_cards_household_id'))
        batch_op.drop_index(batch_op.f('ix_household_cards_created_at'))

    op.drop_table('household_cards')
    with op.batch_alter_table('cash_events', schema=None) as batch_op:
        batch_op.drop_index('ix_cash_events_merchant_scheduled')
        batch_op.drop_index(batch_op.f('ix_cash_events_created_at'))

    op.drop_table('cash_events')
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_index('ix_analysis_results_merchant_created')
        batch_op.drop_index(batch_op.f('ix_analysis_results_is_stale'))
        batch_op.drop_index(batch_op.f('ix_analysis_results_created_at'))

    op.drop_table('analysis_results')
    with op.batch_alter_table('source_records', schema=None) as batch_op:
        batch_op.drop_index('ix_source_records_merchant_created')
        batch_op.drop_index(batch_op.f('ix_source_records_import_batch_id'))
        batch_op.drop_index(batch_op.f('ix_source_records_created_at'))
        batch_op.drop_index(batch_op.f('ix_source_records_content_hash'))

    op.drop_table('source_records')
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenarios_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_scenarios_created_at'))

    op.drop_table('scenarios')
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_households_owner_id'))
        batch_op.drop_index(batch_op.f('ix_households_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_households_invite_code'))
        batch_op.drop_index(batch_op.f('ix_households_created_at'))

    op.drop_table('households')
    with op.batch_alter_table('business_account_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_account_snapshots_snapshot_at'))
        batch_op.drop_index(batch_op.f('ix_business_account_snapshots_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_business_account_snapshots_created_at'))

    op.drop_table('business_account_snapshots')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_created_at'))

    op.drop_table('user_roles')
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_refresh_sessions_user_active')
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_created_at'))

    op.drop_table('refresh_sessions')
    with op.batch_alter_table('merchant_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchant_profiles_created_at'))

    op.drop_table('merchant_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_resource')
        batch_op.drop_index(batch_op.f('ix_audit_logs_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index('ix_audit_logs_actor_created')
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
