"""add import batches

Revision ID: 0ee06e0f0f90
Revises: 0053fb3fa9b7
Create Date: 2026-10-02 14:42:59.614813
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import sqlalchemy as sa

revision: str = '0ee06e0f0f90'
down_revision: str | None = '0053fb3fa9b7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('stored_file_name', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('encoding', sa.String(length=32), nullable=False),
    sa.Column('delimiter', sa.String(length=4), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('mapping', sa.JSON(), nullable=False),
    sa.Column('parsed_rows', sa.JSON(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('invalid_rows', sa.Integer(), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=False),
    sa.Column('created_rows', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('committed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant_profiles.id'], name=op.f('fk_import_batches_merchant_id_merchant_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches'))
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batches_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_batches_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_import_batches_merchant_created', ['merchant_id', 'created_at'], unique=False)
        batch_op.create_index('ix_import_batches_status', ['merchant_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index('ix_import_batches_status')
        batch_op.drop_index('ix_import_batches_merchant_created')
        batch_op.drop_index(batch_op.f('ix_import_batches_created_at'))
        batch_op.drop_index(batch_op.f('ix_import_batches_content_hash'))

    op.drop_table('import_batches')
    # ### end Alembic commands ###
