"""add enhancement history and settlement foundation

Revision ID: 6e784eb94252
Revises: 0ee06e0f0f90
Create Date: 2026-10-03 03:17:13.478854

本迁移只做增量新增，不删除、不重建任何既有表与数据：

1. 新增 5 张表：``daily_cash_history``、``settlement_records``、
   ``enhancement_runs``、``reserve_advice_confirmations``、
   ``merchant_analysis_states``。
2. 为每个已有商户回填一行 ``merchant_analysis_states``（两个 revision 从 1 开始）。
3. **兼容性数据修正**：计算引擎升级到 2.0.0 后，旧版本产生的 ``analysis_results``
   一律标记为 ``is_stale``。旧口径把期初余额排除在提用上限之外，结论不再可作为
   当前决策依据；这里只打标记，不删除任何历史结果。

关于「缺失日」的口径：``daily_cash_history`` 只保存已确认完整的自然日。
没有记录的日期不代表金额为 0，而是「不清楚」；只有商户在导入时明确确认
「该日期范围内数据完整」后，缺失交易的完整日期才允许聚合为 0。
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '6e784eb94252'
down_revision: str | None = '0ee06e0f0f90'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: 当前引擎版本；更早版本产生的结果统一失效
CURRENT_ENGINE_VERSION = "2.0.0"
STALE_REASON = "计算引擎已升级到 2.0.0：期初余额已纳入提用上限约束，请重新计算"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_cash_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('inflow_cents', sa.Integer(), nullable=False),
    sa.Column('outflow_cents', sa.Integer(), nullable=False),
    sa.Column('source_refs', sa.JSON(), nullable=False),
    sa.Column('import_batch_id', sa.String(length=36), nullable=True),
    sa.Column('completeness_confirmed', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant_profiles.id'], name=op.f('fk_daily_cash_history_merchant_id_merchant_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_cash_history')),
    sa.UniqueConstraint('merchant_id', 'day', name='uq_daily_cash_history_merchant_day')
    )
    with op.batch_alter_table('daily_cash_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_cash_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_cash_history_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index('ix_daily_cash_history_merchant_day', ['merchant_id', 'day'], unique=False)

    op.create_table('enhancement_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('ledger_revision', sa.Integer(), nullable=False),
    sa.Column('history_revision', sa.Integer(), nullable=False),
    sa.Column('basis_hash', sa.String(length=64), nullable=False),
    sa.Column('parameters_json', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('stale_reason', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant_profiles.id'], name=op.f('fk_enhancement_runs_merchant_id_merchant_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enhancement_runs'))
    )
    with op.batch_alter_table('enhancement_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enhancement_runs_basis_hash'), ['basis_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_enhancement_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_enhancement_runs_merchant_created', ['merchant_id', 'created_at'], unique=False)
        batch_op.create_index('ix_enhancement_runs_merchant_stale', ['merchant_id', 'is_stale'], unique=False)

    op.create_table('merchant_analysis_states',
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('ledger_revision', sa.Integer(), nullable=False),
    sa.Column('history_revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant_profiles.id'], name=op.f('fk_merchant_analysis_states_merchant_id_merchant_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('merchant_id', name=op.f('pk_merchant_analysis_states'))
    )
    with op.batch_alter_table('merchant_analysis_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merchant_analysis_states_created_at'), ['created_at'], unique=False)

    op.create_table('reserve_advice_confirmations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('previous_reserve_cents', sa.Integer(), nullable=False),
    sa.Column('suggested_reserve_cents', sa.Integer(), nullable=False),
    sa.Column('confirmed_reserve_cents', sa.Integer(), nullable=False),
    sa.Column('basis_hash', sa.String(length=64), nullable=False),
    sa.Column('ledger_revision', sa.Integer(), nullable=False),
    sa.Column('history_revision', sa.Integer(), nullable=False),
    sa.Column('basis_json', sa.JSON(), nullable=False),
    sa.Column('confirmed_by', sa.String(length=36), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=False),
    sa.Column('analysis_result_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant_profiles.id'], name=op.f('fk_reserve_advice_confirmations_merchant_id_merchant_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reserve_advice_confirmations'))
    )
    with op.batch_alter_table('reserve_advice_confirmations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reserve_advice_confirmations_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_reserve_advice_merchant_created', ['merchant_id', 'created_at'], unique=False)

    op.create_table('settlement_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('external_key', sa.String(length=128), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('actual_at', sa.DateTime(), nullable=True),
    sa.Column('known_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('source_ref', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant_profiles.id'], name=op.f('fk_settlement_records_merchant_id_merchant_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlement_records')),
    sa.UniqueConstraint('merchant_id', 'external_key', name='uq_settlement_records_merchant_external_key')
    )
    with op.batch_alter_table('settlement_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlement_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_settlement_records_merchant_channel', ['merchant_id', 'channel'], unique=False)
        batch_op.create_index('ix_settlement_records_scheduled', ['merchant_id', 'scheduled_at'], unique=False)

    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # 数据兼容（不删除任何历史数据）
    # ------------------------------------------------------------------
    connection = op.get_bind()

    # 1. 为已有商户回填分析状态行
    connection.execute(
        sa.text(
            """
            INSERT INTO merchant_analysis_states
                (merchant_id, ledger_revision, history_revision, created_at, updated_at)
            SELECT id, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
            FROM merchant_profiles
            WHERE id NOT IN (SELECT merchant_id FROM merchant_analysis_states)
            """
        )
    )

    # 2. 旧引擎版本产生的分析结果统一标为失效（只打标记，保留数据）
    connection.execute(
        sa.text(
            """
            UPDATE analysis_results
            SET is_stale = 1,
                stale_reason = :reason,
                updated_at = CURRENT_TIMESTAMP
            WHERE engine_version IS NULL OR engine_version <> :current_version
            """
        ),
        {"reason": STALE_REASON, "current_version": CURRENT_ENGINE_VERSION},
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlement_records', schema=None) as batch_op:
        batch_op.drop_index('ix_settlement_records_scheduled')
        batch_op.drop_index('ix_settlement_records_merchant_channel')
        batch_op.drop_index(batch_op.f('ix_settlement_records_created_at'))

    op.drop_table('settlement_records')
    with op.batch_alter_table('reserve_advice_confirmations', schema=None) as batch_op:
        batch_op.drop_index('ix_reserve_advice_merchant_created')
        batch_op.drop_index(batch_op.f('ix_reserve_advice_confirmations_created_at'))

    op.drop_table('reserve_advice_confirmations')
    with op.batch_alter_table('merchant_analysis_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchant_analysis_states_created_at'))

    op.drop_table('merchant_analysis_states')
    with op.batch_alter_table('enhancement_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_enhancement_runs_merchant_stale')
        batch_op.drop_index('ix_enhancement_runs_merchant_created')
        batch_op.drop_index(batch_op.f('ix_enhancement_runs_created_at'))
        batch_op.drop_index(batch_op.f('ix_enhancement_runs_basis_hash'))

    op.drop_table('enhancement_runs')
    with op.batch_alter_table('daily_cash_history', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_cash_history_merchant_day')
        batch_op.drop_index(batch_op.f('ix_daily_cash_history_import_batch_id'))
        batch_op.drop_index(batch_op.f('ix_daily_cash_history_created_at'))

    op.drop_table('daily_cash_history')
    # ### end Alembic commands ###
